base:
  project: Deep Learning using MlOPS
data_source:
  data_src: source_data

load_data:
  num_classes: 3
  raw_data: source_data
  preprocessed_data: data/processed/
  full_p: /deep_mlops/source_data

train_split:
  split_ratio: 80